Отрисуй меня полностью (часть 1)
htmlacademy-univer-javascript-1/2220049-kekstagram-1 pull request #6
Opened 2022-11-07 13:13 UTC by KazantsevaJane

2022-11-08 16:19 UTC, GennadiyM requested changes

2022-11-08 16:19 UTC, GennadiyM commented on js/data.js
> +const createPhotos = () => Array.from({length: PHOTOS_COUNT}, (value, index) => createNewPhotosData(index + 1));
const createPhotos = () => Array.from({length: PHOTOS_COUNT}, (_, index) => createNewPhotosData(index + 1));

2022-11-08 16:19 UTC, GennadiyM commented on js/main.js
> +import {drowThumbnails} from './thumbnail.js';
import { drowThumbnails } from './thumbnail.js';

2022-11-08 16:19 UTC, GennadiyM commented on js/thumbnail.js
> +};
export const drowThumbnails = (photos)  => {

2022-11-08 16:19 UTC, GennadiyM commented on js/main.js
> +drowThumbnails();
const data = createPhotos();

drowThumbnails(data);

2022-11-08 16:19 UTC, GennadiyM commented on js/thumbnail.js
> +  const photos = createPhotos();
удалить эту строку

2022-11-09 06:36 UTC, KazantsevaJane commented on js/main.js
> +drowThumbnails(createPhotos());
Почему-то в самом комите не отобразился нормально ваш комментарий по этому документу, исправила на:
const data = createPhotos();
drowThumbnails(data);
придет со следующим заданием

2022-11-09 06:41 UTC, merged